config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #index
  # get '/smoothies', to: 'smoothies#index'
  get 'smoothies', to: 'smoothies#index', as: 'smoothies'
  #new
  # get '/smoothies/new', to: 'smoothies#new'
  get 'smoothies/new', to: 'smoothies#new'
  #show
  # get '/smoothies/:id', to: 'smoothies#show'
  get 'smoothies/:id', to: 'smoothies#show', as: 'smoothy'
  #create
  post '/smoothies', to: 'smoothies#create'
  #edit
  # get '/smoothies/:id/edit', to: 'smoothies#edit'
  get 'smoothies/:id/edit', to: 'smoothies#edit'
  #update
  patch '/smoothies/:id/edit', to: 'smoothies#update'
  #destroy
  delete '/smoothies/:id', to: 'smoothies#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    belongs_to :smoothie
end

app/models/smoothie.rb
class Smoothie < ApplicationRecord
    has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController

    def index
        @smoothies = Smoothie.all
    end

    def show
        @smoothie = Smoothie.find(params[:id])
    end

    def create
        @smoothie = Smoothie.create(smoothie_params)
        redirect_to '/smoothies'
    end

    def new
        @smoothie = Smoothie.new
    end

    def edit
        @smoothie = Smoothie.find(params[:id])
    end

    def update
        @smoothie = Smoothie.find(params[:id])
        @smoothie.update(smoothie_params)
        redirect_to smoothies_path(@smoothie)
    end

    def destroy
        @smoothie = Smoothie.find(params[:id])
        @smoothie.destroy
        redirect_to '/smoothies'
    end

    private

    def smoothie_params
        params.require(:smoothie).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/smoothies_helper.rb
module SmoothiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rooty Tooty Blendy Fruity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/smoothies/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @smoothie do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/smoothies/index.html.erb
<h1>List of all our Smoothies</h1>
<% @smoothies.each do |smoothie|%>
<h1><%= smoothie.name %></h1>
<% end %>

app/views/smoothies/new.html.erb
<h1>New Smoothie</h1>
<%= form_for @smoothie do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/smoothies/show.html.erb
<h1>Here is the smoothie you selected</h1>
<h2><%= @smoothie.name %></h2>
<% @smoothie.ingredients.each do |ingredient|%>
<p><%= ingredient.name %></p>
<% end %>
<%= link_to "Delete", smoothy_path, method: :delete, data: { confirm: "Really?" }%>